
export const GET_ERRORS = "GET_ERRORS"
export const CREATE_MESSAGE = "CREATE_MESSAGE"
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const ADD_ARTOBJECT = "ADD_ARTOBJECT"
export const GET_ARTOBJECTS = "GET_ARTOBJECTS"
export const GET_ARTOBJECT = "GET_ARTOBJECT"
export const ADD_SPACE = "ADD_SPACE"
export const GET_SPACES = "GET_SPACES"
export const GET_SPACE = "GET_SPACE"
export const GET_AUTHOR_SPACES = "GET_AUTHOR_SPACES"
export const GET_SCENE = "GET_SCENE"
export const SCENE_LOADING = "SCENE_LOADING"
export const SCENE_LOADED = "SCENE_LOADED"
export const ARTOBJECT_LOADING = "ARTOBJECT_LOADING"











