# Generated by Django 2.1.7 on 2020-05-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artspace', '0002_auto_20190404_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artobject',
            name='upload',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='artobjectshadow',
            name='artobject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artspace.ArtObject'),
        ),
    ]
