# Generated by Django 2.1.7 on 2020-05-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artspace', '0003_auto_20200531_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
