# Generated by Django 2.1.7 on 2020-07-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artspace', '0005_auto_20200710_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='avatar',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
    ]
