# Generated by Django 2.1.7 on 2020-07-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artspace', '0006_space_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='avatar',
            field=models.FileField(blank=True, max_length=80000, upload_to='img/'),
        ),
    ]
