# Generated by Django 2.1.7 on 2020-08-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artspace', '0008_auto_20200723_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='avatar',
        ),
    ]
